# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAs < Formula
  desc "Identity switching for git and GitHub CLI"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.3/git-as_0.1.3_darwin_amd64.tar.gz"
      sha256 "30b0e30e2dee3a78d3eca741d2848ec08d71abfbdbaf9d7ac4bf8ba4f7c79daf"

      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.3/git-as_0.1.3_darwin_arm64.tar.gz"
      sha256 "fa5df21d4f90f7a9248959dedf4aa0e853c5319f9e8bd6f6972db37448a91c57"

      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.3/git-as_0.1.3_linux_amd64.tar.gz"
      sha256 "ea6fc2ec3724f0a9d729d120ac53157ddd656517d3471ffdb8252e58d29e8b96"
      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.3/git-as_0.1.3_linux_arm64.tar.gz"
      sha256 "f2ff6850f43746db6b882b9e4583422ba4b540cdd1d03fe1e6975f325b157ed6"
      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
  end
end
