# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAs < Formula
  desc "Identity switching for git and GitHub CLI"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.1/git-as_0.1.1_darwin_amd64.tar.gz"
      sha256 "315ebc14ad0b5c554bf9c8e814fc6d082be83c5410994879ac727f47c566e87a"

      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.1/git-as_0.1.1_darwin_arm64.tar.gz"
      sha256 "0c37161113f9dbae39d9e229864ac336982d6ab823e0536ffd0fca1153985e17"

      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.1/git-as_0.1.1_linux_amd64.tar.gz"
      sha256 "513ffc3870ab0e73292bc30becb0578500f82c1a02ad809a0427f3b41a55ddfc"
      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.1/git-as_0.1.1_linux_arm64.tar.gz"
      sha256 "c422c4379d21029a5a84652782e4cbf46c1a1c936a9057ebbe15b6b338e442a5"
      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
  end
end
