# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitExplain < Formula
  desc "See your contribution status across git repositories"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.4/git-explain_0.1.4_darwin_amd64.tar.gz"
      sha256 "8e55ca0af789eac0a307477a5b1131766c8acb85fa7764e175250f32a9761772"

      def install
        bin.install "git-explain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.4/git-explain_0.1.4_darwin_arm64.tar.gz"
      sha256 "0126fd557cf4bf6097df2f7d9934ad142fb8f54275e8f646ec66604f6869006d"

      def install
        bin.install "git-explain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.4/git-explain_0.1.4_linux_amd64.tar.gz"
      sha256 "5b4aa3480e6a6ea7d837b931d991f6f5b56b920da7217e2cd10fddb89b1923c0"
      def install
        bin.install "git-explain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.4/git-explain_0.1.4_linux_arm64.tar.gz"
      sha256 "808e721caf0df0d42b1e36f29687fc04f4970ed0ccd8f2299bc01f130f273495"
      def install
        bin.install "git-explain"
      end
    end
  end
end
