# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAs < Formula
  desc "Identity switching for git and GitHub CLI"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.2/git-as_0.1.2_darwin_amd64.tar.gz"
      sha256 "8a77bdf64c7de2fde7c9a6df1d48753eebc59d355f521e3106ba2f7c3a54788c"

      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.2/git-as_0.1.2_darwin_arm64.tar.gz"
      sha256 "c084cd0d7a3751b589537cf6e1f13f5c9ea214a07e8057e3eba5b88b3aeff3f2"

      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.2/git-as_0.1.2_linux_amd64.tar.gz"
      sha256 "cfc6c3e04c3295c809eba677afa944e7eb5f783d7549a030fb5bccafafebf42d"
      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.2/git-as_0.1.2_linux_arm64.tar.gz"
      sha256 "ed35db7ed073ca79a12d0b4af3463c65b7c06e596d30dfef816bbf8c06f52b34"
      def install
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
      end
    end
  end
end
