# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitThisBread < Formula
  desc "Git utilities for developers who knead to understand their repos"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.4/git-this-bread_0.1.4_darwin_amd64.tar.gz"
      sha256 "6501dc596f95d4cf012a9bf2ebde9ea6a3c6fed58ea181050da9934fe3f9d33b"

      def install
        bin.install "git-explain"
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
        bin.install "gh-wtfork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.4/git-this-bread_0.1.4_darwin_arm64.tar.gz"
      sha256 "97327459eeff308aefb6fd07073303867b62c7730b08c6c1654e960f65a29562"

      def install
        bin.install "git-explain"
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
        bin.install "gh-wtfork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.4/git-this-bread_0.1.4_linux_amd64.tar.gz"
      sha256 "0085ef9c623bd29220390c5edd6a5d20cc68b98ae853132943d4cde4ecba8236"
      def install
        bin.install "git-explain"
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
        bin.install "gh-wtfork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.4/git-this-bread_0.1.4_linux_arm64.tar.gz"
      sha256 "7a3a303b3f7d98090a5d14e3f03cb2eb5bc97b6a42e53d3221473a318d229cd0"
      def install
        bin.install "git-explain"
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
        bin.install "gh-wtfork"
      end
    end
  end
end
