# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitThisBread < Formula
  desc "Git utilities for developers who knead to understand their repos"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.5/git-this-bread_0.1.5_darwin_amd64.tar.gz"
      sha256 "7afc4a00fc0ac150a016444cd99ccd522484ac6de4d444490bf1b3bea8765416"

      def install
        bin.install "git-explain"
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
        bin.install "gh-wtfork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.5/git-this-bread_0.1.5_darwin_arm64.tar.gz"
      sha256 "abbde7b4e6ac0aec3c7df1077bdbe9fe2a1b2cc0abed0475dec8785afd238878"

      def install
        bin.install "git-explain"
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
        bin.install "gh-wtfork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.5/git-this-bread_0.1.5_linux_amd64.tar.gz"
      sha256 "c30f5652b4a48953759a10a8cc8a790055d62f905ef2bb69ac883673daba6617"
      def install
        bin.install "git-explain"
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
        bin.install "gh-wtfork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.5/git-this-bread_0.1.5_linux_arm64.tar.gz"
      sha256 "07c58720bb96973a7ca9896ac3ba53ddc463b8968bd7bca2a85a19b133a833d0"
      def install
        bin.install "git-explain"
        bin.install "git-id"
        bin.install "git-as"
        bin.install "gh-as"
        bin.install "gh-wtfork"
      end
    end
  end
end
