# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitExplain < Formula
  desc "See your contribution status across git repositories"
  homepage "https://github.com/jdevera/git-this-bread"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.1/git-explain_0.1.1_darwin_amd64.tar.gz"
      sha256 "9119921fe1f4888915a18cbac072b32896b106c807664a4ef2e476463a626544"

      def install
        bin.install "git-explain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.1/git-explain_0.1.1_darwin_arm64.tar.gz"
      sha256 "ed492a19f8fcfa0f0ec1cde4150d15c77dbf77ca4e461cd14a8fb346dfd3d732"

      def install
        bin.install "git-explain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.1/git-explain_0.1.1_linux_amd64.tar.gz"
      sha256 "4cd93432465be8463988d8b49db34a93beaee90c8f0620a2040cfba5db8c3baa"
      def install
        bin.install "git-explain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/git-this-bread/releases/download/v0.1.1/git-explain_0.1.1_linux_arm64.tar.gz"
      sha256 "3e4e13f37d4ca96f98670692a629b4e473594d735b2e05f969017e955b95a5bf"
      def install
        bin.install "git-explain"
      end
    end
  end
end
