# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShdocNg < Formula
  desc "Documentation generator for shell scripts"
  homepage "https://github.com/jdevera/shdoc-ng"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdevera/shdoc-ng/releases/download/v0.3.0/shdoc-ng_0.3.0_darwin_amd64.tar.gz"
      sha256 "7b0363a0954a4f46a3e0d506b9008ff33462172eaba854a91eff91cc0bf6089d"

      define_method(:install) do
        bin.install "shdoc-ng"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdevera/shdoc-ng/releases/download/v0.3.0/shdoc-ng_0.3.0_darwin_arm64.tar.gz"
      sha256 "08950c2d27f62d0c8f9b3a44634b9eb640b13f39173e5a679b4eeb8f5ce41473"

      define_method(:install) do
        bin.install "shdoc-ng"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/shdoc-ng/releases/download/v0.3.0/shdoc-ng_0.3.0_linux_amd64.tar.gz"
      sha256 "0c827da616c9be1a43721cc367d0e18c991fe9248725691eedc0a64531d77d94"
      define_method(:install) do
        bin.install "shdoc-ng"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdevera/shdoc-ng/releases/download/v0.3.0/shdoc-ng_0.3.0_linux_arm64.tar.gz"
      sha256 "d5c6911914c8257f9ec0104b765e74775e12d2b6bed86d2f5614192d79be3e3b"
      define_method(:install) do
        bin.install "shdoc-ng"
      end
    end
  end

  test do
    system "#{bin}/shdoc-ng", "--version"
  end
end
